import {Exercise, repeatOptions, weightOptions1, weightOptions2} from "./state.interface";


export const EXERCISES: Exercise[] = [
  {
    id: 'b1',
    name: 'bench machine',
    repeatOptions,
    color: 'orange',
    weightOptions: weightOptions2,
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'b2',
    name: 'bench bar',
    repeatOptions,
    color: 'orange',
    weightOptions: weightOptions1,
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'b2',
    name: 'bench dumbbells flat',
    repeatOptions,
    color: 'orange',
    weightOptions: weightOptions1,
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'b3',
    name: 'bench dumbbells incline',
    repeatOptions,
    color: 'orange',
    weightOptions: weightOptions1,
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'b4',
    name: 'bench machine incline',
    repeatOptions,
    color: 'orange',
    weightOptions: weightOptions1,
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'b5',
    name: 'bench smith incline',
    repeatOptions,
    color: 'orange',
    weightOptions: weightOptions1,
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'c1',
    name: 'cables upper chest',
    repeatOptions,
    color: 'orange',
    weightOptions: weightOptions1,
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'dips',
    name: 'dips',
    repeatOptions,
    color: 'orange',
    weightOptions: [],
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'ab1',
    name: 'abs bench decline',
    repeatOptions: [
      15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
      33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    ],
    color: 'red',
    weightOptions: [],
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'ab2',
    name: 'abs roller',
    repeatOptions: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    color: 'red',
    weightOptions: [],
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bk1',
    name: 'pull-down wide grip',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'yellow',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bk2',
    name: 'rowing wide grip',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'yellow',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bk3',
    name: 'barbell rows',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'yellow',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bk4',
    name: 'land mine row',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'yellow',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bk5',
    name: 'pull-down close grip',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'yellow',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bk6',
    name: 'pull-ups. bicep side',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'yellow',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bi1',
    name: 'bicep bar',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'red',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'bi2',
    name: 'bicep dumbbell',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'red',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh1',
    name: 'push dumbbell',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh2',
    name: 'push barbell',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh3',
    name: 'push machine',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh4',
    name: 'plate up/down',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh5',
    name: 'side fly',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh6',
    name: 'face pull',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh7',
    name: 'rear deltoid fly machine',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
  {
    id: 'sh8',
    name: 'shrugs',
    repeatOptions,
    weightOptions: weightOptions1,
    color: 'green',
    weightUnit: 'kg',
    description: '',
  },
];
