import { Exercise } from "./state.interface";

export const EXERCISES: Exercise[] = [
  { id: 'b1',  name: 'bench machine flat',       color: 'orange',   description: 'press machine flat press.' },
  { id: 'b2',  name: 'bench bar flat',           color: 'orange',   description: 'flat bench barbell press.' },
  { id: 'b22', name: 'bench dumbbells flat',     color: 'orange',   description: 'flat bench with dumbbells.' },
  { id: 'b3',  name: 'bench dumbbells incline',  color: 'orange',   description: 'incline bench with dumbbells.' },
  { id: 'b4',  name: 'bench machine incline',    color: 'orange',   description: 'press machine incline press.' },
  { id: 'b5',  name: 'bench smith incline',      color: 'orange',   description: 'bench press on smith. incline or flat.' },
  { id: 'b6',  name: 'bench flies',              color: 'orange',   description: 'bench fly machine.' },
  { id: 'c1',  name: 'cables upper chest',       color: 'orange',   description: 'cable press from bottom up. upper chest.' },
  { id: 'b7',  name: 'bench dumbbells upper',    color: 'orange',   description: 'incline bench with dumbbells upper chest.' },
  { id: 'dips',name: 'dips',                     color: 'orange',  description: 'dips. triceps or lower chest' },
  { id: 'ab1', name: 'abs bench decline',        color: 'red',      description: 'abs on decline bench.' },
  { id: 'ab2', name: 'abs roller',               color: 'red',     description: 'abs with roller.' },
  { id: 'ab3', name: 'abs hang',                 color: 'red',     description: 'abs on bar lifting legs up and down.' },
  { id: 'ab4', name: 'abs штафета',              color: 'red',     description: 'abs legs up and down.' },
  { id: 'bk1', name: 'pull-down',                color: 'yellow',   description: '' },
  { id: 'bk2', name: 'rowing machine',           color: 'yellow',   description: '' },
  { id: 'bk3', name: 'barbell rows',             color: 'yellow',   description: '' },
  { id: 'bk4', name: 'land mine row',            color: 'yellow',   description: '' },
  { id: 'bk5', name: 'pull-down close grip(old)',color: 'yellow',   description: '' },
  { id: 'bk6', name: 'pull-ups',                 color: 'yellow',   description: '' },
  { id: 'bk7', name: 'back',                     color: 'yellow',   description: '' },
  { id: 'bi1', name: 'bicep bar',                color: 'pink',     description: '' },
  { id: 'bi2', name: 'bicep dumbbell',           color: 'pink',     description: '' },
  { id: 'sh1', name: 'push dumbbell',            color: 'green',    description: '' },
  { id: 'sh2', name: 'push barbell',             color: 'green',    description: '' },
  { id: 'sh3', name: 'push machine',             color: 'green',    description: '' },
  { id: 'sh4', name: 'plate up/down',            color: 'green',    description: '' },
  { id: 'sh5', name: 'side fly',                 color: 'green',    description: '' },
  { id: 'sh6', name: 'face pull',                color: 'green',    description: '' },
  { id: 'sh7', name: 'rear deltoid fly machine', color: 'green',    description: '' },
  { id: 'sh8', name: 'shrugs',                   color: 'green',    description: '' },
  { id: 'sh9', name: 'landmine push up',         color: 'green',    description: '' },
  { id: 'l1',  name: 'hip-thrust',               color: 'blue',     description: '' },
  { id: 'l2',  name: 'rdl-dumbbells',            color: 'blue',     description: '' },
  { id: 'l3',  name: 'rdl-bar',                  color: 'blue',     description: '' },
  { id: 'l4',  name: 'leg-press',                color: 'blue',     description: '' },
  { id: 'l5',  name: 'leg-abduction',            color: 'blue',     description: '' },
  { id: 'l6',  name: 'leg-curl-ham',             color: 'blue',     description: '' },
  { id: 'l7',  name: 'leg-curl-quad',            color: 'blue',     description: '' },
  { id: 'l8',  name: 'squats',                   color: 'blue',     description: '' },
  { id: 'l9',  name: 'lunges',                   color: 'blue',     description: '' },
  { id: 'run', name: 'running',                  color: 'red',     description: 'Running around. Zone 2 baby!' },
  { id: 'hike',name: 'hike',                     color: 'red',     description: 'Hiking around' },
  { id: 'hang',name: 'dead hang',                color: 'purple', description: 'Daily Hang for 60 sec lats engaged' },
  { id: 'th',  name: 'threadmill',               color: 'purple', description: 'Threadmill. Run. Backward walk. Sprints.' },
  { id: 'sw',  name: 'swimming',                 color: 'purple', description: 'Swimming pool. 500m 1km 2km' },
  { id: 'em',  name: 'empty',                    color: 'black',  description: 'Place Holder for new exercise.' },
];
